# baseurl = "http://h-sao.github.io"
baseurl = "http://h-sao.com"
title = "Effectiveさお"
languageCode = "en-us"
disqusShortname = "harukasao"
MetaDataFormat = "toml"
theme = "hyde-x"
paginate = 10

[author]
    name = "遥佐保/はるかさお/Sao Haruka"

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    # post = "/blog/:year/:month/:day/:title/"
    post = "/blog/:year/:month/:day/:filename/"

[indexes]
    # Optional. Use if you want tags and lists.
    category = "categories"

#
# All parameters below here are optional and can be mixed and matched.
#
[params]

    # If false display full article contents in blog index.
    # Otherwise show description and 'read on' link to individual blog post page.
    # Default (if ommitted) is true.
    truncate = false

    # Used when a given page doesn't set its own.
    defaultDescription = "遥佐保/はるかさお/Sao Haruka"
    defaultKeywords = "C++,C#"

    # Changes sidebar background and link/accent colours.
    # See below for more colour options.
    # This also works: "theme-base-08 layout-reverse", or just "layout-reverse".
    theme = "theme-base-08"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "sunburst"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "C++/C#/Windowsで遊んでいますMicrosoft MVP for Windows Platform Development [Jan,2015-Dec,2015]/ Microsoft MVP for Client Development [Jan,2014-Dec,2014]/ Microsoft MVP for Client App Dev [Jan,2010-Dec,2013]"

    # Metadata used to drive integrations.
#    googleAuthorship = "Your Google+ profile ID"
    googleAnalytics = "UA-66721712-1"
    gravatarHash = "0eb58d770d6e4766150ef7cb6cdce3c7"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/h-sao"
    bitbucket = ""
    linkedin = ""
#    googleplus = "https://plus.google.com/106462274497419316996"
#    facebook = "https://www.facebook.com/xxxxx"
    twitter = "https://twitter.com/hr_sao"
